### ISSUE TITLE
Intergating with MyBB

### ISSUE THREAD

**Issue by ghost** [desgyz/MailChimpMyBBPlugin#1]
Hi

After trying every plugin I could find I came across this plugin to integrate Mailchimp with MyBB 1.8.
How do I add the opt in on the registration page? The readme does not provide instructions :)

**Comment by audibailey** [comment]
Go through this wiki page and it should have all the required information to get you started, thanks for checking this plugin out!

https://github.com/desgyz/MailChimpMyBBPlugin/wiki/Configure-Plugin

**Comment by ghost** [comment]
Thank you for getting back to me. Highly appreciated ! :+1:

**Comment by audibailey** [comment]
All good, if you have more questions or any suggestions, post them I'll be happy too respond to them :)
